# GCP Settings
gcp_project   = "austin-rent"
gcp_region    = "us-central1"
gcp_auth_file = "/workspaces/AustinRent/secrets/tofu-key.json"
# Backend Bucket
tofu_backend_bucket_name = "tofu-state-austin-rent"
storage_class            = "REGIONAL"
github_organization_repo = "CupOfGeo/Austin-Rent"
github_organization      = "CupOfGeo"
