secrets:
  TEST: YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa1RkTEVZZWdEbnI1Rmgyb2RzdEc3L1hkWXozYWk5RkZmMlk5TUpFSWljCm9ldTJBN2xEYXlFaFdiNmJsUXR4eklxTllBV2JjTi9Yb2czTUxrRElnWmsKLS0tIDNYbWNvNnFUeDFrb2VZZ3FCcGsyOWNtZ25hQXMrWi91cGY5endYeGo2UlEK61yW+mYcM0my9NH6B2X3o2L3CfCNveVXm9PtV5V/0R7w2Ue2aWUrrEUL3SXEwSNIMAQ=
  DB_HOST: YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYVhQYm5wdzdVMm00aitmeXhPM1ozL1NGYmhRN0gyU1FmcTlnOW1qa0M0Cmo2TWdvQnZXWVZvNkJRTndsa2FJVHpFWDJxVENrNEJOcDlkQ3RkQllXaGMKLS0tIHlFbDcybkhJQlJpVjRSUmh1azFrSlEzRmVLcGo0OW51NTFhVjd1MXVxc3cKQR7ifVkb3Xz6z3XOyS7ealZJe9y4ADypMIprIkGdStzMMpT0Ckp7LnKXG8unmyg=
  DB_PASS: YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL25jV0hsSnJNeVZHVlNWM0pTWkJQVk5nMGc4QUs0RFluWHQ1YnhncEN3CllXM3Vqc3BoaDJPMmJqTTBFTHBaSkQ2S0JpWmRKeDR6b0syY29ydWo0RnMKLS0tIEdZdytER05HbFlDVXl0STE5VWhFTTBuWGZOYUlPd2RRRThGYXI5dk1TdG8KYzNO8tydg8X5xPLn8zYV+atWr1DHVLlYrP0LPWZbgEYD5PEj5gAPbRxQH3DBFTwTrFcduYRKsXk3

env_vars:
  ENVIRONMENT: DEV
