secrets:
  DB_PASS: YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL25jV0hsSnJNeVZHVlNWM0pTWkJQVk5nMGc4QUs0RFluWHQ1YnhncEN3CllXM3Vqc3BoaDJPMmJqTTBFTHBaSkQ2S0JpWmRKeDR6b0syY29ydWo0RnMKLS0tIEdZdytER05HbFlDVXl0STE5VWhFTTBuWGZOYUlPd2RRRThGYXI5dk1TdG8KYzNO8tydg8X5xPLn8zYV+atWr1DHVLlYrP0LPWZbgEYD5PEj5gAPbRxQH3DBFTwTrFcduYRKsXk3

env_vars:
  ENVIRONMENT: LOCAL
  DB_HOST: 0.0.0.0
